name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:   # 👈 this enables manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        env:
         DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build project
        run: npm run build
        env:
         DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
         host: ${{ secrets.EC2_HOST }}
         username: ubuntu
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
          set -e

          cd ~/next_vercel

          echo "📥 Pulling latest code..."
          git fetch origin
          git reset --hard origin/main

          echo "📦 Installing dependencies (light mode)..."
          npm ci --omit=dev --no-audit --no-fund

          echo "⚙️ Generating Prisma client..."
          npx prisma generate

          echo "🏗️ Building Next.js (low memory)..."
          NODE_OPTIONS="--max-old-space-size=512" npm run build

          echo "🚀 Restarting app..."
          pm2 reload nextjs-app || pm2 start npm --name "nextjs-app" -- start

          echo "✅ Deployment complete"